import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const requiredDocs = [
  'docs/start-here/welcome.mdx',
  'docs/start-here/core-concepts.mdx',
  'docs/start-here/launch-guide.mdx',
  'docs/start-here/workspaces-and-agents.mdx',
  'docs/build-your-agent/agent-setup.mdx',
  'docs/build-your-agent/knowledge-base.mdx',
  'docs/automate/workflow-overview.mdx',
  'docs/automate/workflow-actions.mdx',
  'docs/automate/reminders.mdx',
  'docs/automate/follow-ups.mdx',
  'docs/channels/connect-channels.mdx',
  'docs/bookings/services.mdx',
  'docs/bookings/availability.mdx',
  'docs/bookings/calendar.mdx',
  'docs/engage/inbox.mdx',
  'docs/engage/contacts.mdx',
  'docs/engage/quick-replies.mdx',
  'docs/engage/message-templates.mdx',
  'docs/engage/broadcast.mdx',
  'docs/team/lead-assignment.mdx',
  'docs/team/workspace-and-team.mdx',
  'docs/team/roles-and-permissions.mdx',
  'docs/insights/overview-and-analytics.mdx',
  'docs/insights/usage-and-billing.mdx',
  'docs/help/troubleshooting.mdx',
  'docs/help/contact-support.mdx',
];

const requiredSidebarLabels = [
  'Start here',
  'Build your AI agent',
  'Automate conversations',
  'Connect channels',
  'Manage bookings',
  'Engage customers',
  'Manage your team',
  'Measure and improve',
  'Troubleshooting and support',
];

function read(relativePath) {
  return readFileSync(path.join(root, relativePath), 'utf8');
}

test('ships every required product guide with useful front matter', () => {
  for (const relativePath of requiredDocs) {
    assert.equal(existsSync(path.join(root, relativePath)), true, `${relativePath} is missing`);
    const source = read(relativePath);
    assert.match(source, /^---\n[\s\S]*title: .+[\s\S]*description: .+[\s\S]*---/);
    assert.ok(source.split(/\s+/).length >= 90, `${relativePath} is too thin`);
  }
});

test('uses an explicit task-oriented sidebar', () => {
  const sidebar = read('sidebars.ts');
  for (const label of requiredSidebarLabels) {
    assert.ok(sidebar.includes(`label: '${label}'`), `${label} sidebar group is missing`);
  }
  assert.equal(sidebar.includes("type: 'autogenerated'"), false);
});

test('removes all starter tutorial and demo content', () => {
  assert.equal(existsSync(path.join(root, 'docs/tutorial-basics')), false);
  assert.equal(existsSync(path.join(root, 'docs/tutorial-extras')), false);
  assert.equal(existsSync(path.join(root, 'blog/2019-05-28-first-blog-post.mdx')), false);
  assert.equal(existsSync(path.join(root, 'src/pages/markdown-page.mdx')), false);
});
