import assert from 'node:assert/strict';
import {existsSync, readFileSync} from 'node:fs';
import {test} from 'node:test';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const requiredDocs = [
  'docs/start-here/welcome.mdx',
  'docs/start-here/launch-guide.mdx',
  'docs/start-here/workspaces-and-agents.mdx',
  'docs/build-your-agent/agent-setup.mdx',
  'docs/build-your-agent/knowledge-base.mdx',
  'docs/automate/workflow-overview.mdx',
  'docs/automate/reminders.mdx',
  'docs/automate/follow-ups.mdx',
  'docs/channels/connect-channels.mdx',
  'docs/bookings/services.mdx',
  'docs/bookings/availability.mdx',
  'docs/bookings/calendar.mdx',
  'docs/engage/inbox.mdx',
  'docs/engage/contacts.mdx',
  'docs/engage/quick-replies.mdx',
  'docs/engage/message-templates.mdx',
  'docs/engage/broadcast.mdx',
  'docs/team/lead-assignment.mdx',
  'docs/team/workspace-and-team.mdx',
  'docs/team/roles-and-permissions.mdx',
  'docs/insights/overview-and-analytics.mdx',
  'docs/insights/usage-and-billing.mdx',
  'docs/help/troubleshooting.mdx',
  'docs/help/contact-support.mdx',
];

const coreConceptDocs = [
  'build-your-agent/agent-setup',
  'build-your-agent/knowledge-base',
  'automate/workflow-overview',
  'bookings/services',
  'bookings/availability',
  'channels/connect-channels',
];

const resourceDocs = [
  'engage/inbox',
  'engage/contacts',
  'bookings/calendar',
  'engage/message-templates',
  'automate/reminders',
  'automate/follow-ups',
  'engage/quick-replies',
  'engage/broadcast',
  'team/workspace-and-team',
  'team/roles-and-permissions',
  'team/lead-assignment',
  'insights/overview-and-analytics',
  'insights/usage-and-billing',
];

const requiredSidebarLabels = [
  'Getting started',
  'Core Concepts',
  'Resources',
  'Help and support',
];

function read(relativePath) {
  return readFileSync(path.join(root, relativePath), 'utf8');
}

function sidebarItemsBlock(sidebar, label) {
  return sidebar.match(
    new RegExp(`label: '${label}',[\\s\\S]*?items: \\[([\\s\\S]*?)\\],`),
  )?.[1];
}

test('ships every required product guide with useful front matter', () => {
  for (const relativePath of requiredDocs) {
    assert.equal(existsSync(path.join(root, relativePath)), true, `${relativePath} is missing`);
    const source = read(relativePath);
    assert.match(source, /^---\n[\s\S]*title: .+[\s\S]*description: .+[\s\S]*---/);
    assert.ok(source.split(/\s+/).length >= 90, `${relativePath} is too thin`);
    if (relativePath !== 'docs/start-here/welcome.mdx') {
      assert.ok(
        source.includes('## Overview'),
        `${relativePath} is missing ## Overview`,
      );
    }
  }
  assert.equal(existsSync(path.join(root, 'docs/start-here/core-concepts.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/automate/workflow-actions.mdx')), false);
  assert.ok(
    read('docs/automate/workflow-overview.mdx').includes('## Choose an action type'),
  );
});

test('keeps Core Concepts to the essentials and the rest in Resources', () => {
  const sidebar = read('sidebars.ts');
  const coreBlock = sidebarItemsBlock(sidebar, 'Core Concepts');
  const resourceBlock = sidebarItemsBlock(sidebar, 'Resources');
  assert.ok(coreBlock, 'Core Concepts items block is missing');
  assert.ok(resourceBlock, 'Resources items block is missing');

  const coreIds = [...coreBlock.matchAll(/'([^']+)'/g)].map((match) => match[1]);
  assert.equal(coreIds.length, coreConceptDocs.length);
  assert.deepEqual(coreIds, coreConceptDocs);
  for (const docId of coreConceptDocs) {
    assert.ok(coreBlock.includes(`'${docId}'`), `Core Concepts missing ${docId}`);
  }
  for (const docId of resourceDocs) {
    assert.ok(resourceBlock.includes(`'${docId}'`), `Resources missing ${docId}`);
    assert.equal(
      coreBlock.includes(`'${docId}'`),
      false,
      `${docId} should not be in Core Concepts`,
    );
  }
  assert.equal(coreBlock.includes('team/workspace-and-team'), false);
  assert.equal(coreBlock.includes('team/roles-and-permissions'), false);
});

test('uses an explicit task-oriented sidebar', () => {
  const sidebar = read('sidebars.ts');
  for (const label of requiredSidebarLabels) {
    assert.ok(sidebar.includes(`label: '${label}'`), `${label} sidebar group is missing`);
  }
  assert.equal(sidebar.includes("type: 'autogenerated'"), false);
});

test('styles sidebar groups as bold section headers with indented links', () => {
  const css = read('src/css/custom.css');
  const sidebar = read('sidebars.ts');

  assert.ok(css.includes('.theme-doc-sidebar-item-category-level-1'));
  assert.ok(css.includes('pointer-events: none'));
  assert.match(css, /\.theme-doc-sidebar-item-category-level-1 \.menu__link--sublist-caret::after \{[\s\S]*display: none;/);
  assert.match(css, /\.menu__link--active:not\(\.menu__link--sublist\) \{[\s\S]*border-radius: 0\.5rem|background: var\(--kilobot-muted\)/);
  assert.ok(sidebar.includes('collapsible: false'));
  assert.ok(sidebar.includes('collapsed: false'));
  assert.equal(existsSync(path.join(root, 'src/theme/DocSidebarItem/Category/index.tsx')), false);
});

test('uses whitespace for sidebar topic groups and a subtle navbar edge', () => {
  const css = read('src/css/custom.css');
  const navbarCss = read('src/css/navbar.css');
  const navbarRule = navbarCss.match(/\.navbar \{[^}]*\}/)?.[0] ?? '';
  const categoryRule = css.match(/\.theme-doc-sidebar-item-category-level-1 \{[^}]*\}/)?.[0] ?? '';

  assert.match(navbarRule, /border-bottom:/);
  assert.doesNotMatch(categoryRule, /border-bottom:/);
  assert.match(categoryRule, /margin-top:\s*1\.15rem\s*!important/);
  assert.match(
    css,
    /\.menu__list-item:not\(\.theme-doc-sidebar-item-category-level-1\)/,
  );
});

test('removes all starter tutorial and demo content', () => {
  assert.equal(existsSync(path.join(root, 'docs/tutorial-basics/create-a-document.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/tutorial-extras/manage-docs-versions.mdx')), false);
  assert.equal(existsSync(path.join(root, 'blog/2019-05-28-first-blog-post.mdx')), false);
  assert.equal(existsSync(path.join(root, 'src/pages/markdown-page.mdx')), false);
  assert.equal(existsSync(path.join(root, 'src/components/HomepageFeatures/index.tsx')), false);
});
