import assert from 'node:assert/strict';
import {existsSync, readFileSync} from 'node:fs';
import {test} from 'node:test';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const requiredDocs = [
  'docs/start-here/welcome.mdx',
  'docs/start-here/quick-start.mdx',
  'docs/start-here/workspaces-and-agents.mdx',
  'docs/build-your-agent/agent-setup.mdx',
  'docs/build-your-agent/knowledge-base.mdx',
  'docs/automate/send-messages-and-assets.mdx',
  'docs/automate/human-in-the-loop.mdx',
  'docs/automate/automate-bookings.mdx',
  'docs/automate/reminders.mdx',
  'docs/automate/follow-ups.mdx',
  'docs/channels/connect-channels.mdx',
  'docs/channels/website-widget.mdx',
  'docs/channels/whatsapp.mdx',
  'docs/channels/instagram.mdx',
  'docs/channels/messenger.mdx',
  'docs/bookings/services.mdx',
  'docs/bookings/availability.mdx',
  'docs/bookings/calendar.mdx',
  'docs/engage/inbox.mdx',
  'docs/engage/contacts.mdx',
  'docs/engage/message-templates.mdx',
  'docs/engage/broadcast.mdx',
  'docs/team/lead-assignment.mdx',
  'docs/team/workspace-and-team.mdx',
  'docs/team/roles-and-permissions.mdx',
  'docs/help/troubleshooting.mdx',
  'docs/help/contact-support.mdx',
];

const requiredSidebarLabels = [
  'Getting started',
  'Agent',
  'Channels',
  'Bookings',
  'Workflows',
  'Outreach',
  'Teams',
  'Releases',
  'Help and support',
];

function read(relativePath) {
  return readFileSync(path.join(root, relativePath), 'utf8');
}

test('ships every required product guide with useful front matter', () => {
  for (const relativePath of requiredDocs) {
    assert.equal(existsSync(path.join(root, relativePath)), true, `${relativePath} is missing`);
    const source = read(relativePath);
    assert.match(source, /^---\n[\s\S]*title: .+[\s\S]*description: .+[\s\S]*---/);
    assert.ok(source.split(/\s+/).length >= 70, `${relativePath} is too thin`);
  }
  assert.equal(existsSync(path.join(root, 'docs/start-here/core-concepts.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/automate/workflow-actions.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/automate/workflow-overview.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/automate/build-and-test.mdx')), false);
});

test('keeps retired guides outside the public docs input', () => {
  const sidebar = read('sidebars.ts');
  const retiredPaths = [
    'docs/engage/quick-replies.mdx',
    'docs/insights/overview-and-analytics.mdx',
    'docs/insights/usage-and-billing.mdx',
  ];
  for (const retiredPath of retiredPaths) {
    assert.equal(existsSync(path.join(root, retiredPath)), false);
  }
  assert.equal(sidebar.includes('quick-replies'), false);
  assert.equal(sidebar.includes('overview-and-analytics'), false);
  assert.equal(sidebar.includes('usage-and-billing'), false);
});

test('uses an explicit task-oriented sidebar', () => {
  const sidebar = read('sidebars.ts');
  for (const label of requiredSidebarLabels) {
    assert.ok(sidebar.includes(`label: '${label}'`), `${label} sidebar group is missing`);
  }
  assert.equal(sidebar.includes("type: 'autogenerated'"), false);
});

test('styles sidebar groups as bold section headers with indented links', () => {
  const css = read('src/css/custom.css');
  const sidebar = read('sidebars.ts');

  assert.ok(css.includes('.theme-doc-sidebar-item-category-level-1'));
  assert.ok(css.includes('pointer-events: none'));
  assert.match(css, /\.theme-doc-sidebar-item-category-level-1 \.menu__link--sublist-caret::after \{[\s\S]*display: none;/);
  assert.match(css, /\.menu__link--active:not\(\.menu__link--sublist\) \{[\s\S]*border-radius: 0\.5rem|background: var\(--kilobot-muted\)/);
  assert.ok(sidebar.includes('collapsible: false'));
  assert.ok(sidebar.includes('collapsed: false'));
  assert.equal(existsSync(path.join(root, 'src/theme/DocSidebarItem/Category/index.tsx')), false);
});

test('uses whitespace for sidebar topic groups and a subtle navbar edge', () => {
  const css = read('src/css/custom.css');
  const navbarCss = read('src/css/navbar.css');
  const navbarRule = navbarCss.match(/\.navbar \{[^}]*\}/)?.[0] ?? '';
  const categoryRule = css.match(/\.theme-doc-sidebar-item-category-level-1 \{[^}]*\}/)?.[0] ?? '';

  assert.match(navbarRule, /border-bottom:/);
  assert.doesNotMatch(categoryRule, /border-bottom:/);
  assert.match(categoryRule, /margin-top:\s*1\.15rem\s*!important/);
  assert.match(
    css,
    /\.menu__list-item:not\(\.theme-doc-sidebar-item-category-level-1\)/,
  );
});

test('removes all starter tutorial and demo content', () => {
  assert.equal(existsSync(path.join(root, 'docs/tutorial-basics/create-a-document.mdx')), false);
  assert.equal(existsSync(path.join(root, 'docs/tutorial-extras/manage-docs-versions.mdx')), false);
  assert.equal(existsSync(path.join(root, 'blog/2019-05-28-first-blog-post.mdx')), false);
  assert.equal(existsSync(path.join(root, 'src/pages/markdown-page.mdx')), false);
  assert.equal(existsSync(path.join(root, 'src/components/HomepageFeatures/index.tsx')), false);
});

test('keeps all new code modules below the workspace limit', () => {
  const codeFiles = [
    'docusaurus.config.ts',
    'sidebars.ts',
    'src/css/custom.css',
    'src/css/navbar.css',
    'src/css/toc.css',
    'src/css/pagination.css',
    'src/theme/Navbar/Logo/index.tsx',
    'src/theme/Navbar/Logo/styles.module.css',
    'src/theme/TOCCollapsible/CollapseButton/index.tsx',
    'src/theme/TOCCollapsible/CollapseButton/styles.module.css',
    'src/theme/MDXComponents/Img/index.tsx',
    'src/theme/MDXComponents/Img/styles.module.css',
    'src/theme/MDXComponents/Img/index.test.tsx',
    'src/theme/DocRoot/Layout/Main/index.tsx',
    'src/theme/DocRoot/Layout/Main/styles.module.css',
    'src/components/DocPathGrid.tsx',
    'src/components/DocPathGrid.module.css',
    'src/components/DocPathTile.tsx',
    'src/components/DocPathTile.module.css',
    'src/components/DocCard.tsx',
    'src/components/DocCard.module.css',
    'src/components/DocQuickstartBanner.tsx',
    'src/components/DocQuickstartBanner.module.css',
  ];
  for (const relativePath of codeFiles) {
    assert.equal(existsSync(path.join(root, relativePath)), true, `${relativePath} is missing`);
    const lineCount = read(relativePath).split('\n').length;
    assert.ok(lineCount <= 300, `${relativePath} has ${lineCount} lines`);
  }
});
