/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adminUsageCostAggregateQuery from "../adminUsageCostAggregateQuery.js";
import type * as adminUsageCostAggregation from "../adminUsageCostAggregation.js";
import type * as adminUsageCosts from "../adminUsageCosts.js";
import type * as agentAccess from "../agentAccess.js";
import type * as agentCostAggregateModel from "../agentCostAggregateModel.js";
import type * as agentModelMigration from "../agentModelMigration.js";
import type * as agentOverview from "../agentOverview.js";
import type * as agentOverviewAbandonments from "../agentOverviewAbandonments.js";
import type * as agentOverviewAggregates from "../agentOverviewAggregates.js";
import type * as agentOverviewClose from "../agentOverviewClose.js";
import type * as agentOverviewDaily from "../agentOverviewDaily.js";
import type * as agentOverviewMessages from "../agentOverviewMessages.js";
import type * as agentOverviewModel from "../agentOverviewModel.js";
import type * as agentOverviewSentiment from "../agentOverviewSentiment.js";
import type * as agentOverviewTestHelpers from "../agentOverviewTestHelpers.js";
import type * as agentOverviewTopics from "../agentOverviewTopics.js";
import type * as agentRuntime from "../agentRuntime.js";
import type * as agentUsage from "../agentUsage.js";
import type * as agentUsageAggregatesModel from "../agentUsageAggregatesModel.js";
import type * as agentValidators from "../agentValidators.js";
import type * as agents from "../agents.js";
import type * as aggregates from "../aggregates.js";
import type * as analytics from "../analytics.js";
import type * as analyticsConversationContributionModel from "../analyticsConversationContributionModel.js";
import type * as analyticsConversationMemberContributions from "../analyticsConversationMemberContributions.js";
import type * as analyticsConversationProjection from "../analyticsConversationProjection.js";
import type * as analyticsCronSchedule from "../analyticsCronSchedule.js";
import type * as analyticsDirtyDispatcher from "../analyticsDirtyDispatcher.js";
import type * as analyticsDirtyRequest from "../analyticsDirtyRequest.js";
import type * as analyticsInsightRecords from "../analyticsInsightRecords.js";
import type * as analyticsInsights from "../analyticsInsights.js";
import type * as analyticsInsightsContract from "../analyticsInsightsContract.js";
import type * as analyticsInsightsPool from "../analyticsInsightsPool.js";
import type * as analyticsMessageProjection from "../analyticsMessageProjection.js";
import type * as analyticsMetricContributions from "../analyticsMetricContributions.js";
import type * as analyticsMetricModel from "../analyticsMetricModel.js";
import type * as analyticsProjectionMigration from "../analyticsProjectionMigration.js";
import type * as analyticsProjectionRepair from "../analyticsProjectionRepair.js";
import type * as analyticsProjectionState from "../analyticsProjectionState.js";
import type * as analyticsProjectionStateModel from "../analyticsProjectionStateModel.js";
import type * as analyticsProjectionVerification from "../analyticsProjectionVerification.js";
import type * as analyticsProjectionWorker from "../analyticsProjectionWorker.js";
import type * as analyticsRefreshRequest from "../analyticsRefreshRequest.js";
import type * as analyticsRefreshWorker from "../analyticsRefreshWorker.js";
import type * as analyticsTimeRange from "../analyticsTimeRange.js";
import type * as analyticsTopicProjection from "../analyticsTopicProjection.js";
import type * as analyticsTopicRecords from "../analyticsTopicRecords.js";
import type * as appointmentBooking_access from "../appointmentBooking/access.js";
import type * as appointmentBooking_availability from "../appointmentBooking/availability.js";
import type * as appointmentBooking_bookAppointment from "../appointmentBooking/bookAppointment.js";
import type * as appointmentBooking_bookingEvents from "../appointmentBooking/bookingEvents.js";
import type * as appointmentBooking_calendarHelpers from "../appointmentBooking/calendarHelpers.js";
import type * as appointmentBooking_calendarManualBooking from "../appointmentBooking/calendarManualBooking.js";
import type * as appointmentBooking_cancellations from "../appointmentBooking/cancellations.js";
import type * as appointmentBooking_completion from "../appointmentBooking/completion.js";
import type * as appointmentBooking_confirmations from "../appointmentBooking/confirmations.js";
import type * as appointmentBooking_currentBooking from "../appointmentBooking/currentBooking.js";
import type * as appointmentBooking_customerBookings from "../appointmentBooking/customerBookings.js";
import type * as appointmentBooking_editBookingStatus from "../appointmentBooking/editBookingStatus.js";
import type * as appointmentBooking_editing from "../appointmentBooking/editing.js";
import type * as appointmentBooking_fields from "../appointmentBooking/fields.js";
import type * as appointmentBooking_manualBooking from "../appointmentBooking/manualBooking.js";
import type * as appointmentBooking_manualBookingCore from "../appointmentBooking/manualBookingCore.js";
import type * as appointmentBooking_manualBookingFields from "../appointmentBooking/manualBookingFields.js";
import type * as appointmentBooking_serviceAssignments from "../appointmentBooking/serviceAssignments.js";
import type * as appointmentBooking_services from "../appointmentBooking/services.js";
import type * as appointmentBooking_sessionStore from "../appointmentBooking/sessionStore.js";
import type * as appointmentBooking_sessions from "../appointmentBooking/sessions.js";
import type * as appointmentBooking_staffBooking from "../appointmentBooking/staffBooking.js";
import type * as appointmentBooking_statusTransition from "../appointmentBooking/statusTransition.js";
import type * as appointmentBooking_types from "../appointmentBooking/types.js";
import type * as appointmentBooking_updateAppointment from "../appointmentBooking/updateAppointment.js";
import type * as appointmentBooking_validators from "../appointmentBooking/validators.js";
import type * as appointmentBookingSessionStatus from "../appointmentBookingSessionStatus.js";
import type * as auth from "../auth.js";
import type * as authUtils from "../authUtils.js";
import type * as avatar from "../avatar.js";
import type * as avatarConversation from "../avatarConversation.js";
import type * as avatarCore from "../avatarCore.js";
import type * as avatarEmbed from "../avatarEmbed.js";
import type * as avatarProvider from "../avatarProvider.js";
import type * as avatarSession from "../avatarSession.js";
import type * as backfillEvents from "../backfillEvents.js";
import type * as billingAddOns from "../billingAddOns.js";
import type * as billingScope from "../billingScope.js";
import type * as broadcastChatContent from "../broadcastChatContent.js";
import type * as broadcastMessageValidators from "../broadcastMessageValidators.js";
import type * as broadcastPool from "../broadcastPool.js";
import type * as calendarEvents from "../calendarEvents.js";
import type * as calendarFormatUtils from "../calendarFormatUtils.js";
import type * as channelAgentThreadCleanup from "../channelAgentThreadCleanup.js";
import type * as channelSyncPools from "../channelSyncPools.js";
import type * as channels from "../channels.js";
import type * as chat_aiReplyMedia from "../chat/aiReplyMedia.js";
import type * as chat_aiReplyMessages from "../chat/aiReplyMessages.js";
import type * as chat_aiReplyOutput from "../chat/aiReplyOutput.js";
import type * as chat_broadcastMessageMetadata from "../chat/broadcastMessageMetadata.js";
import type * as chat_channelSend from "../chat/channelSend.js";
import type * as chat_identityPriorityPrompt from "../chat/identityPriorityPrompt.js";
import type * as chat_inboundMediaFetch from "../chat/inboundMediaFetch.js";
import type * as chat_inboundMediaModel from "../chat/inboundMediaModel.js";
import type * as chat_inbox from "../chat/inbox.js";
import type * as chat_inboxActions from "../chat/inboxActions.js";
import type * as chat_inboxAudioIngest from "../chat/inboxAudioIngest.js";
import type * as chat_inboxImageIngest from "../chat/inboxImageIngest.js";
import type * as chat_inboxMessageMapping from "../chat/inboxMessageMapping.js";
import type * as chat_mediaManifest from "../chat/mediaManifest.js";
import type * as chat_mediaSendLogs from "../chat/mediaSendLogs.js";
import type * as chat_mediaToolResults from "../chat/mediaToolResults.js";
import type * as chat_mediaUrlExtractor from "../chat/mediaUrlExtractor.js";
import type * as chat_reactions from "../chat/reactions.js";
import type * as chat_readReceipts from "../chat/readReceipts.js";
import type * as chat_responseFormatting from "../chat/responseFormatting.js";
import type * as chat_streaming from "../chat/streaming.js";
import type * as chat_threads from "../chat/threads.js";
import type * as chat_toolPrompt from "../chat/toolPrompt.js";
import type * as chat_whatsappMediaIngest from "../chat/whatsappMediaIngest.js";
import type * as chat_workflowActionExecution from "../chat/workflowActionExecution.js";
import type * as chat_workflowActionPlanner from "../chat/workflowActionPlanner.js";
import type * as chat_workflowAutomationMessageMetadata from "../chat/workflowAutomationMessageMetadata.js";
import type * as chat_workflowMediaFallback from "../chat/workflowMediaFallback.js";
import type * as chat_workflowPrompt from "../chat/workflowPrompt.js";
import type * as cloudflare from "../cloudflare.js";
import type * as contactAdmin from "../contactAdmin.js";
import type * as contactAdminAuth from "../contactAdminAuth.js";
import type * as contactAdminMigration from "../contactAdminMigration.js";
import type * as contactAdminNotify from "../contactAdminNotify.js";
import type * as contactAdminShared from "../contactAdminShared.js";
import type * as contactRequests from "../contactRequests.js";
import type * as conversationLogs from "../conversationLogs.js";
import type * as conversations from "../conversations.js";
import type * as creditEntries from "../creditEntries.js";
import type * as creditLogs from "../creditLogs.js";
import type * as creditPeriodPool from "../creditPeriodPool.js";
import type * as creditPlanReset from "../creditPlanReset.js";
import type * as creditSourceBreakdown from "../creditSourceBreakdown.js";
import type * as creditUsageAnalytics from "../creditUsageAnalytics.js";
import type * as credits from "../credits.js";
import type * as crons from "../crons.js";
import type * as customerImportPool from "../customerImportPool.js";
import type * as customerSearch from "../customerSearch.js";
import type * as customerSearchMigration from "../customerSearchMigration.js";
import type * as customers from "../customers.js";
import type * as devReset from "../devReset.js";
import type * as followUpPool from "../followUpPool.js";
import type * as followUpQueries from "../followUpQueries.js";
import type * as freeCheckout from "../freeCheckout.js";
import type * as freePlanDowngrade from "../freePlanDowngrade.js";
import type * as freePlanDowngradeState from "../freePlanDowngradeState.js";
import type * as freePlanSubscriptionUpdate from "../freePlanSubscriptionUpdate.js";
import type * as http from "../http.js";
import type * as inboundMediaBatch from "../inboundMediaBatch.js";
import type * as inboundMediaUnderstanding from "../inboundMediaUnderstanding.js";
import type * as inboxPools from "../inboxPools.js";
import type * as instagramAuth from "../instagramAuth.js";
import type * as instagramConnect from "../instagramConnect.js";
import type * as instagramSend from "../instagramSend.js";
import type * as instagramSync from "../instagramSync.js";
import type * as instagramWebhook from "../instagramWebhook.js";
import type * as knowledgeBase from "../knowledgeBase.js";
import type * as knowledgeBaseImages from "../knowledgeBaseImages.js";
import type * as latestStripeSubscription from "../latestStripeSubscription.js";
import type * as leadRouting_assign from "../leadRouting/assign.js";
import type * as leadRouting_eligibility from "../leadRouting/eligibility.js";
import type * as leadRouting_helpers from "../leadRouting/helpers.js";
import type * as leadRouting_provision from "../leadRouting/provision.js";
import type * as leadRouting_schedules from "../leadRouting/schedules.js";
import type * as leadRouting_settings from "../leadRouting/settings.js";
import type * as llm_ilmu from "../llm/ilmu.js";
import type * as llm_languageModel from "../llm/languageModel.js";
import type * as llm_modelCost from "../llm/modelCost.js";
import type * as llm_modelPricing from "../llm/modelPricing.js";
import type * as llm_openRouter from "../llm/openRouter.js";
import type * as llm_retryPolicy from "../llm/retryPolicy.js";
import type * as media_attachments from "../media/attachments.js";
import type * as media_publicUrls from "../media/publicUrls.js";
import type * as media_r2 from "../media/r2.js";
import type * as media_r2Client from "../media/r2Client.js";
import type * as mediaPools from "../mediaPools.js";
import type * as messages from "../messages.js";
import type * as messengerAuth from "../messengerAuth.js";
import type * as messengerConnect from "../messengerConnect.js";
import type * as messengerSend from "../messengerSend.js";
import type * as messengerSync from "../messengerSync.js";
import type * as messengerWebhook from "../messengerWebhook.js";
import type * as metaWebhookShared from "../metaWebhookShared.js";
import type * as oauthSessions from "../oauthSessions.js";
import type * as oauthShared from "../oauthShared.js";
import type * as orgRoles from "../orgRoles.js";
import type * as organizationsAdmin from "../organizationsAdmin.js";
import type * as planCatalog from "../planCatalog.js";
import type * as planStripe from "../planStripe.js";
import type * as plans from "../plans.js";
import type * as posthog from "../posthog.js";
import type * as quickReplies from "../quickReplies.js";
import type * as referralCodeMigration from "../referralCodeMigration.js";
import type * as referralCodeRecords from "../referralCodeRecords.js";
import type * as referralProgramConfig from "../referralProgramConfig.js";
import type * as referralRedemption from "../referralRedemption.js";
import type * as referrals from "../referrals.js";
import type * as serviceAvailabilityMigration from "../serviceAvailabilityMigration.js";
import type * as signedRequest from "../signedRequest.js";
import type * as stripe from "../stripe.js";
import type * as stripeBillingSessions from "../stripeBillingSessions.js";
import type * as stripeCheckout from "../stripeCheckout.js";
import type * as stripeSubscriptionEvents from "../stripeSubscriptionEvents.js";
import type * as teamAccess from "../teamAccess.js";
import type * as teamDeletion_access from "../teamDeletion/access.js";
import type * as teamDeletion_channelDisconnect from "../teamDeletion/channelDisconnect.js";
import type * as teamDeletion_external from "../teamDeletion/external.js";
import type * as teamDeletion_externalGuard from "../teamDeletion/externalGuard.js";
import type * as teamDeletion_externalResourceCleanup from "../teamDeletion/externalResourceCleanup.js";
import type * as teamDeletion_externalResourceState from "../teamDeletion/externalResourceState.js";
import type * as teamDeletion_externalState from "../teamDeletion/externalState.js";
import type * as teamDeletion_isolation from "../teamDeletion/isolation.js";
import type * as teamDeletion_local from "../teamDeletion/local.js";
import type * as teamDeletion_localDescendants from "../teamDeletion/localDescendants.js";
import type * as teamDeletion_manifest from "../teamDeletion/manifest.js";
import type * as teamDeletion_model from "../teamDeletion/model.js";
import type * as teamDeletion_pool from "../teamDeletion/pool.js";
import type * as teamDeletion_request from "../teamDeletion/request.js";
import type * as teamDeletion_verify from "../teamDeletion/verify.js";
import type * as teamDeletion_worker from "../teamDeletion/worker.js";
import type * as teamHelpers from "../teamHelpers.js";
import type * as teamInvitationRecords from "../teamInvitationRecords.js";
import type * as teamInvitations from "../teamInvitations.js";
import type * as teamMembers from "../teamMembers.js";
import type * as teamRoles from "../teamRoles.js";
import type * as teamStripePlanResolver from "../teamStripePlanResolver.js";
import type * as teams from "../teams.js";
import type * as telegramNotifications_config from "../telegramNotifications/config.js";
import type * as telegramNotifications_dispatch from "../telegramNotifications/dispatch.js";
import type * as telegramNotifications_events from "../telegramNotifications/events.js";
import type * as telegramNotifications_kinds from "../telegramNotifications/kinds.js";
import type * as telegramNotifications_phone from "../telegramNotifications/phone.js";
import type * as telegramNotifications_pool from "../telegramNotifications/pool.js";
import type * as telegramNotifications_preferences from "../telegramNotifications/preferences.js";
import type * as telegramNotifications_queue from "../telegramNotifications/queue.js";
import type * as telegramNotifications_subscriptionAccess from "../telegramNotifications/subscriptionAccess.js";
import type * as telegramNotifications_subscriptions from "../telegramNotifications/subscriptions.js";
import type * as telegramNotifications_telegramApi from "../telegramNotifications/telegramApi.js";
import type * as telegramNotifications_testMessage from "../telegramNotifications/testMessage.js";
import type * as telegramNotifications_testPreview from "../telegramNotifications/testPreview.js";
import type * as telegramNotifications_token from "../telegramNotifications/token.js";
import type * as telegramNotifications_updateParser from "../telegramNotifications/updateParser.js";
import type * as telegramNotifications_validators from "../telegramNotifications/validators.js";
import type * as telegramNotifications_verification from "../telegramNotifications/verification.js";
import type * as telegramNotifications_worker from "../telegramNotifications/worker.js";
import type * as telegramWebhook from "../telegramWebhook.js";
import type * as testUtils from "../testUtils.js";
import type * as timeZoneDateKeys from "../timeZoneDateKeys.js";
import type * as topUpEntrySourceMigration from "../topUpEntrySourceMigration.js";
import type * as triggers from "../triggers.js";
import type * as usageMonthKey from "../usageMonthKey.js";
import type * as users from "../users.js";
import type * as webWidget from "../webWidget.js";
import type * as webWidgetAccess from "../webWidgetAccess.js";
import type * as webWidgetAdmin from "../webWidgetAdmin.js";
import type * as webWidgetCore from "../webWidgetCore.js";
import type * as webWidgetTraditional from "../webWidgetTraditional.js";
import type * as webWidgetValidators from "../webWidgetValidators.js";
import type * as whatsappBroadcast from "../whatsappBroadcast.js";
import type * as whatsappChannelGuard from "../whatsappChannelGuard.js";
import type * as whatsappConnectionAttemptUtils from "../whatsappConnectionAttemptUtils.js";
import type * as whatsappEmbeddedSignup from "../whatsappEmbeddedSignup.js";
import type * as whatsappFollowUp from "../whatsappFollowUp.js";
import type * as whatsappHistoryDiagnostics from "../whatsappHistoryDiagnostics.js";
import type * as whatsappMessagingLimit from "../whatsappMessagingLimit.js";
import type * as whatsappMetaSignup from "../whatsappMetaSignup.js";
import type * as whatsappPhone from "../whatsappPhone.js";
import type * as whatsappSend from "../whatsappSend.js";
import type * as whatsappSignupCompletion from "../whatsappSignupCompletion.js";
import type * as whatsappSignupOrchestration from "../whatsappSignupOrchestration.js";
import type * as whatsappSkipContacts from "../whatsappSkipContacts.js";
import type * as whatsappSync from "../whatsappSync.js";
import type * as whatsappTemplateLifecycle from "../whatsappTemplateLifecycle.js";
import type * as whatsappTemplateMediaGraph from "../whatsappTemplateMediaGraph.js";
import type * as whatsappTemplateMediaPool from "../whatsappTemplateMediaPool.js";
import type * as whatsappTemplateMetaUpload from "../whatsappTemplateMetaUpload.js";
import type * as whatsappTemplateMigration from "../whatsappTemplateMigration.js";
import type * as whatsappTemplatePresentation from "../whatsappTemplatePresentation.js";
import type * as whatsappTemplateQueries from "../whatsappTemplateQueries.js";
import type * as whatsappTemplateRender from "../whatsappTemplateRender.js";
import type * as whatsappTemplateSendPayload from "../whatsappTemplateSendPayload.js";
import type * as whatsappTemplateSendPayloadBuild from "../whatsappTemplateSendPayloadBuild.js";
import type * as whatsappTemplateUpdate from "../whatsappTemplateUpdate.js";
import type * as whatsappTemplateUpdateHelpers from "../whatsappTemplateUpdateHelpers.js";
import type * as whatsappTemplateWebhook from "../whatsappTemplateWebhook.js";
import type * as whatsappTemplates from "../whatsappTemplates.js";
import type * as whatsappTemplatesAction from "../whatsappTemplatesAction.js";
import type * as whatsappWebhook from "../whatsappWebhook.js";
import type * as workflowAppointmentServices from "../workflowAppointmentServices.js";
import type * as workflowAutomationConfig from "../workflowAutomationConfig.js";
import type * as workflowAutomationCost from "../workflowAutomationCost.js";
import type * as workflowAutomationCostMigration from "../workflowAutomationCostMigration.js";
import type * as workflowAutomationHistory from "../workflowAutomationHistory.js";
import type * as workflowAutomationLifecycle from "../workflowAutomationLifecycle.js";
import type * as workflowAutomationMessageActivity from "../workflowAutomationMessageActivity.js";
import type * as workflowAutomationOutbound from "../workflowAutomationOutbound.js";
import type * as workflowAutomationReconciliation from "../workflowAutomationReconciliation.js";
import type * as workflowAutomationSave from "../workflowAutomationSave.js";
import type * as workflowAutomationSchema from "../workflowAutomationSchema.js";
import type * as workflowAutomationValidators from "../workflowAutomationValidators.js";
import type * as workflowCore from "../workflowCore.js";
import type * as workflowDraftSave from "../workflowDraftSave.js";
import type * as workflowDraftValidation from "../workflowDraftValidation.js";
import type * as workflowFollowUpPool from "../workflowFollowUpPool.js";
import type * as workflowFollowUpRuntime from "../workflowFollowUpRuntime.js";
import type * as workflowFollowUpStartAfterMigration from "../workflowFollowUpStartAfterMigration.js";
import type * as workflowFollowUpTimer from "../workflowFollowUpTimer.js";
import type * as workflowFollowUpWorker from "../workflowFollowUpWorker.js";
import type * as workflowGraphSaveValidators from "../workflowGraphSaveValidators.js";
import type * as workflowLayout from "../workflowLayout.js";
import type * as workflowMedia from "../workflowMedia.js";
import type * as workflowMediaDeletion from "../workflowMediaDeletion.js";
import type * as workflowMediaInternal from "../workflowMediaInternal.js";
import type * as workflowMediaShared from "../workflowMediaShared.js";
import type * as workflowMessageGraphSave from "../workflowMessageGraphSave.js";
import type * as workflowMigrations from "../workflowMigrations.js";
import type * as workflowNodeCanvasControls from "../workflowNodeCanvasControls.js";
import type * as workflowNodeConfig from "../workflowNodeConfig.js";
import type * as workflowNodeReadiness from "../workflowNodeReadiness.js";
import type * as workflowNodeReadinessMigration from "../workflowNodeReadinessMigration.js";
import type * as workflowNodeRemoval from "../workflowNodeRemoval.js";
import type * as workflowReminderPool from "../workflowReminderPool.js";
import type * as workflowReminderRuntime from "../workflowReminderRuntime.js";
import type * as workflowReminderSchedule from "../workflowReminderSchedule.js";
import type * as workflowReminderWorker from "../workflowReminderWorker.js";
import type * as workflowReset from "../workflowReset.js";
import type * as workflowRuntimeContext from "../workflowRuntimeContext.js";
import type * as workflowTemplateUsage from "../workflowTemplateUsage.js";
import type * as workflowTemplateUsageSchema from "../workflowTemplateUsageSchema.js";
import type * as workflowValidators from "../workflowValidators.js";
import type * as workflowWhatsappTemplateSender from "../workflowWhatsappTemplateSender.js";
import type * as workflows from "../workflows.js";
import type * as workosClient from "../workosClient.js";
import type * as workosOrganizationActions from "../workosOrganizationActions.js";
import type * as workosWebhook from "../workosWebhook.js";
import type * as workpool from "../workpool.js";
import type * as workspaceSetupChecklist from "../workspaceSetupChecklist.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  adminUsageCostAggregateQuery: typeof adminUsageCostAggregateQuery;
  adminUsageCostAggregation: typeof adminUsageCostAggregation;
  adminUsageCosts: typeof adminUsageCosts;
  agentAccess: typeof agentAccess;
  agentCostAggregateModel: typeof agentCostAggregateModel;
  agentModelMigration: typeof agentModelMigration;
  agentOverview: typeof agentOverview;
  agentOverviewAbandonments: typeof agentOverviewAbandonments;
  agentOverviewAggregates: typeof agentOverviewAggregates;
  agentOverviewClose: typeof agentOverviewClose;
  agentOverviewDaily: typeof agentOverviewDaily;
  agentOverviewMessages: typeof agentOverviewMessages;
  agentOverviewModel: typeof agentOverviewModel;
  agentOverviewSentiment: typeof agentOverviewSentiment;
  agentOverviewTestHelpers: typeof agentOverviewTestHelpers;
  agentOverviewTopics: typeof agentOverviewTopics;
  agentRuntime: typeof agentRuntime;
  agentUsage: typeof agentUsage;
  agentUsageAggregatesModel: typeof agentUsageAggregatesModel;
  agentValidators: typeof agentValidators;
  agents: typeof agents;
  aggregates: typeof aggregates;
  analytics: typeof analytics;
  analyticsConversationContributionModel: typeof analyticsConversationContributionModel;
  analyticsConversationMemberContributions: typeof analyticsConversationMemberContributions;
  analyticsConversationProjection: typeof analyticsConversationProjection;
  analyticsCronSchedule: typeof analyticsCronSchedule;
  analyticsDirtyDispatcher: typeof analyticsDirtyDispatcher;
  analyticsDirtyRequest: typeof analyticsDirtyRequest;
  analyticsInsightRecords: typeof analyticsInsightRecords;
  analyticsInsights: typeof analyticsInsights;
  analyticsInsightsContract: typeof analyticsInsightsContract;
  analyticsInsightsPool: typeof analyticsInsightsPool;
  analyticsMessageProjection: typeof analyticsMessageProjection;
  analyticsMetricContributions: typeof analyticsMetricContributions;
  analyticsMetricModel: typeof analyticsMetricModel;
  analyticsProjectionMigration: typeof analyticsProjectionMigration;
  analyticsProjectionRepair: typeof analyticsProjectionRepair;
  analyticsProjectionState: typeof analyticsProjectionState;
  analyticsProjectionStateModel: typeof analyticsProjectionStateModel;
  analyticsProjectionVerification: typeof analyticsProjectionVerification;
  analyticsProjectionWorker: typeof analyticsProjectionWorker;
  analyticsRefreshRequest: typeof analyticsRefreshRequest;
  analyticsRefreshWorker: typeof analyticsRefreshWorker;
  analyticsTimeRange: typeof analyticsTimeRange;
  analyticsTopicProjection: typeof analyticsTopicProjection;
  analyticsTopicRecords: typeof analyticsTopicRecords;
  "appointmentBooking/access": typeof appointmentBooking_access;
  "appointmentBooking/availability": typeof appointmentBooking_availability;
  "appointmentBooking/bookAppointment": typeof appointmentBooking_bookAppointment;
  "appointmentBooking/bookingEvents": typeof appointmentBooking_bookingEvents;
  "appointmentBooking/calendarHelpers": typeof appointmentBooking_calendarHelpers;
  "appointmentBooking/calendarManualBooking": typeof appointmentBooking_calendarManualBooking;
  "appointmentBooking/cancellations": typeof appointmentBooking_cancellations;
  "appointmentBooking/completion": typeof appointmentBooking_completion;
  "appointmentBooking/confirmations": typeof appointmentBooking_confirmations;
  "appointmentBooking/currentBooking": typeof appointmentBooking_currentBooking;
  "appointmentBooking/customerBookings": typeof appointmentBooking_customerBookings;
  "appointmentBooking/editBookingStatus": typeof appointmentBooking_editBookingStatus;
  "appointmentBooking/editing": typeof appointmentBooking_editing;
  "appointmentBooking/fields": typeof appointmentBooking_fields;
  "appointmentBooking/manualBooking": typeof appointmentBooking_manualBooking;
  "appointmentBooking/manualBookingCore": typeof appointmentBooking_manualBookingCore;
  "appointmentBooking/manualBookingFields": typeof appointmentBooking_manualBookingFields;
  "appointmentBooking/serviceAssignments": typeof appointmentBooking_serviceAssignments;
  "appointmentBooking/services": typeof appointmentBooking_services;
  "appointmentBooking/sessionStore": typeof appointmentBooking_sessionStore;
  "appointmentBooking/sessions": typeof appointmentBooking_sessions;
  "appointmentBooking/staffBooking": typeof appointmentBooking_staffBooking;
  "appointmentBooking/statusTransition": typeof appointmentBooking_statusTransition;
  "appointmentBooking/types": typeof appointmentBooking_types;
  "appointmentBooking/updateAppointment": typeof appointmentBooking_updateAppointment;
  "appointmentBooking/validators": typeof appointmentBooking_validators;
  appointmentBookingSessionStatus: typeof appointmentBookingSessionStatus;
  auth: typeof auth;
  authUtils: typeof authUtils;
  avatar: typeof avatar;
  avatarConversation: typeof avatarConversation;
  avatarCore: typeof avatarCore;
  avatarEmbed: typeof avatarEmbed;
  avatarProvider: typeof avatarProvider;
  avatarSession: typeof avatarSession;
  backfillEvents: typeof backfillEvents;
  billingAddOns: typeof billingAddOns;
  billingScope: typeof billingScope;
  broadcastChatContent: typeof broadcastChatContent;
  broadcastMessageValidators: typeof broadcastMessageValidators;
  broadcastPool: typeof broadcastPool;
  calendarEvents: typeof calendarEvents;
  calendarFormatUtils: typeof calendarFormatUtils;
  channelAgentThreadCleanup: typeof channelAgentThreadCleanup;
  channelSyncPools: typeof channelSyncPools;
  channels: typeof channels;
  "chat/aiReplyMedia": typeof chat_aiReplyMedia;
  "chat/aiReplyMessages": typeof chat_aiReplyMessages;
  "chat/aiReplyOutput": typeof chat_aiReplyOutput;
  "chat/broadcastMessageMetadata": typeof chat_broadcastMessageMetadata;
  "chat/channelSend": typeof chat_channelSend;
  "chat/identityPriorityPrompt": typeof chat_identityPriorityPrompt;
  "chat/inboundMediaFetch": typeof chat_inboundMediaFetch;
  "chat/inboundMediaModel": typeof chat_inboundMediaModel;
  "chat/inbox": typeof chat_inbox;
  "chat/inboxActions": typeof chat_inboxActions;
  "chat/inboxAudioIngest": typeof chat_inboxAudioIngest;
  "chat/inboxImageIngest": typeof chat_inboxImageIngest;
  "chat/inboxMessageMapping": typeof chat_inboxMessageMapping;
  "chat/mediaManifest": typeof chat_mediaManifest;
  "chat/mediaSendLogs": typeof chat_mediaSendLogs;
  "chat/mediaToolResults": typeof chat_mediaToolResults;
  "chat/mediaUrlExtractor": typeof chat_mediaUrlExtractor;
  "chat/reactions": typeof chat_reactions;
  "chat/readReceipts": typeof chat_readReceipts;
  "chat/responseFormatting": typeof chat_responseFormatting;
  "chat/streaming": typeof chat_streaming;
  "chat/threads": typeof chat_threads;
  "chat/toolPrompt": typeof chat_toolPrompt;
  "chat/whatsappMediaIngest": typeof chat_whatsappMediaIngest;
  "chat/workflowActionExecution": typeof chat_workflowActionExecution;
  "chat/workflowActionPlanner": typeof chat_workflowActionPlanner;
  "chat/workflowAutomationMessageMetadata": typeof chat_workflowAutomationMessageMetadata;
  "chat/workflowMediaFallback": typeof chat_workflowMediaFallback;
  "chat/workflowPrompt": typeof chat_workflowPrompt;
  cloudflare: typeof cloudflare;
  contactAdmin: typeof contactAdmin;
  contactAdminAuth: typeof contactAdminAuth;
  contactAdminMigration: typeof contactAdminMigration;
  contactAdminNotify: typeof contactAdminNotify;
  contactAdminShared: typeof contactAdminShared;
  contactRequests: typeof contactRequests;
  conversationLogs: typeof conversationLogs;
  conversations: typeof conversations;
  creditEntries: typeof creditEntries;
  creditLogs: typeof creditLogs;
  creditPeriodPool: typeof creditPeriodPool;
  creditPlanReset: typeof creditPlanReset;
  creditSourceBreakdown: typeof creditSourceBreakdown;
  creditUsageAnalytics: typeof creditUsageAnalytics;
  credits: typeof credits;
  crons: typeof crons;
  customerImportPool: typeof customerImportPool;
  customerSearch: typeof customerSearch;
  customerSearchMigration: typeof customerSearchMigration;
  customers: typeof customers;
  devReset: typeof devReset;
  followUpPool: typeof followUpPool;
  followUpQueries: typeof followUpQueries;
  freeCheckout: typeof freeCheckout;
  freePlanDowngrade: typeof freePlanDowngrade;
  freePlanDowngradeState: typeof freePlanDowngradeState;
  freePlanSubscriptionUpdate: typeof freePlanSubscriptionUpdate;
  http: typeof http;
  inboundMediaBatch: typeof inboundMediaBatch;
  inboundMediaUnderstanding: typeof inboundMediaUnderstanding;
  inboxPools: typeof inboxPools;
  instagramAuth: typeof instagramAuth;
  instagramConnect: typeof instagramConnect;
  instagramSend: typeof instagramSend;
  instagramSync: typeof instagramSync;
  instagramWebhook: typeof instagramWebhook;
  knowledgeBase: typeof knowledgeBase;
  knowledgeBaseImages: typeof knowledgeBaseImages;
  latestStripeSubscription: typeof latestStripeSubscription;
  "leadRouting/assign": typeof leadRouting_assign;
  "leadRouting/eligibility": typeof leadRouting_eligibility;
  "leadRouting/helpers": typeof leadRouting_helpers;
  "leadRouting/provision": typeof leadRouting_provision;
  "leadRouting/schedules": typeof leadRouting_schedules;
  "leadRouting/settings": typeof leadRouting_settings;
  "llm/ilmu": typeof llm_ilmu;
  "llm/languageModel": typeof llm_languageModel;
  "llm/modelCost": typeof llm_modelCost;
  "llm/modelPricing": typeof llm_modelPricing;
  "llm/openRouter": typeof llm_openRouter;
  "llm/retryPolicy": typeof llm_retryPolicy;
  "media/attachments": typeof media_attachments;
  "media/publicUrls": typeof media_publicUrls;
  "media/r2": typeof media_r2;
  "media/r2Client": typeof media_r2Client;
  mediaPools: typeof mediaPools;
  messages: typeof messages;
  messengerAuth: typeof messengerAuth;
  messengerConnect: typeof messengerConnect;
  messengerSend: typeof messengerSend;
  messengerSync: typeof messengerSync;
  messengerWebhook: typeof messengerWebhook;
  metaWebhookShared: typeof metaWebhookShared;
  oauthSessions: typeof oauthSessions;
  oauthShared: typeof oauthShared;
  orgRoles: typeof orgRoles;
  organizationsAdmin: typeof organizationsAdmin;
  planCatalog: typeof planCatalog;
  planStripe: typeof planStripe;
  plans: typeof plans;
  posthog: typeof posthog;
  quickReplies: typeof quickReplies;
  referralCodeMigration: typeof referralCodeMigration;
  referralCodeRecords: typeof referralCodeRecords;
  referralProgramConfig: typeof referralProgramConfig;
  referralRedemption: typeof referralRedemption;
  referrals: typeof referrals;
  serviceAvailabilityMigration: typeof serviceAvailabilityMigration;
  signedRequest: typeof signedRequest;
  stripe: typeof stripe;
  stripeBillingSessions: typeof stripeBillingSessions;
  stripeCheckout: typeof stripeCheckout;
  stripeSubscriptionEvents: typeof stripeSubscriptionEvents;
  teamAccess: typeof teamAccess;
  "teamDeletion/access": typeof teamDeletion_access;
  "teamDeletion/channelDisconnect": typeof teamDeletion_channelDisconnect;
  "teamDeletion/external": typeof teamDeletion_external;
  "teamDeletion/externalGuard": typeof teamDeletion_externalGuard;
  "teamDeletion/externalResourceCleanup": typeof teamDeletion_externalResourceCleanup;
  "teamDeletion/externalResourceState": typeof teamDeletion_externalResourceState;
  "teamDeletion/externalState": typeof teamDeletion_externalState;
  "teamDeletion/isolation": typeof teamDeletion_isolation;
  "teamDeletion/local": typeof teamDeletion_local;
  "teamDeletion/localDescendants": typeof teamDeletion_localDescendants;
  "teamDeletion/manifest": typeof teamDeletion_manifest;
  "teamDeletion/model": typeof teamDeletion_model;
  "teamDeletion/pool": typeof teamDeletion_pool;
  "teamDeletion/request": typeof teamDeletion_request;
  "teamDeletion/verify": typeof teamDeletion_verify;
  "teamDeletion/worker": typeof teamDeletion_worker;
  teamHelpers: typeof teamHelpers;
  teamInvitationRecords: typeof teamInvitationRecords;
  teamInvitations: typeof teamInvitations;
  teamMembers: typeof teamMembers;
  teamRoles: typeof teamRoles;
  teamStripePlanResolver: typeof teamStripePlanResolver;
  teams: typeof teams;
  "telegramNotifications/config": typeof telegramNotifications_config;
  "telegramNotifications/dispatch": typeof telegramNotifications_dispatch;
  "telegramNotifications/events": typeof telegramNotifications_events;
  "telegramNotifications/kinds": typeof telegramNotifications_kinds;
  "telegramNotifications/phone": typeof telegramNotifications_phone;
  "telegramNotifications/pool": typeof telegramNotifications_pool;
  "telegramNotifications/preferences": typeof telegramNotifications_preferences;
  "telegramNotifications/queue": typeof telegramNotifications_queue;
  "telegramNotifications/subscriptionAccess": typeof telegramNotifications_subscriptionAccess;
  "telegramNotifications/subscriptions": typeof telegramNotifications_subscriptions;
  "telegramNotifications/telegramApi": typeof telegramNotifications_telegramApi;
  "telegramNotifications/testMessage": typeof telegramNotifications_testMessage;
  "telegramNotifications/testPreview": typeof telegramNotifications_testPreview;
  "telegramNotifications/token": typeof telegramNotifications_token;
  "telegramNotifications/updateParser": typeof telegramNotifications_updateParser;
  "telegramNotifications/validators": typeof telegramNotifications_validators;
  "telegramNotifications/verification": typeof telegramNotifications_verification;
  "telegramNotifications/worker": typeof telegramNotifications_worker;
  telegramWebhook: typeof telegramWebhook;
  testUtils: typeof testUtils;
  timeZoneDateKeys: typeof timeZoneDateKeys;
  topUpEntrySourceMigration: typeof topUpEntrySourceMigration;
  triggers: typeof triggers;
  usageMonthKey: typeof usageMonthKey;
  users: typeof users;
  webWidget: typeof webWidget;
  webWidgetAccess: typeof webWidgetAccess;
  webWidgetAdmin: typeof webWidgetAdmin;
  webWidgetCore: typeof webWidgetCore;
  webWidgetTraditional: typeof webWidgetTraditional;
  webWidgetValidators: typeof webWidgetValidators;
  whatsappBroadcast: typeof whatsappBroadcast;
  whatsappChannelGuard: typeof whatsappChannelGuard;
  whatsappConnectionAttemptUtils: typeof whatsappConnectionAttemptUtils;
  whatsappEmbeddedSignup: typeof whatsappEmbeddedSignup;
  whatsappFollowUp: typeof whatsappFollowUp;
  whatsappHistoryDiagnostics: typeof whatsappHistoryDiagnostics;
  whatsappMessagingLimit: typeof whatsappMessagingLimit;
  whatsappMetaSignup: typeof whatsappMetaSignup;
  whatsappPhone: typeof whatsappPhone;
  whatsappSend: typeof whatsappSend;
  whatsappSignupCompletion: typeof whatsappSignupCompletion;
  whatsappSignupOrchestration: typeof whatsappSignupOrchestration;
  whatsappSkipContacts: typeof whatsappSkipContacts;
  whatsappSync: typeof whatsappSync;
  whatsappTemplateLifecycle: typeof whatsappTemplateLifecycle;
  whatsappTemplateMediaGraph: typeof whatsappTemplateMediaGraph;
  whatsappTemplateMediaPool: typeof whatsappTemplateMediaPool;
  whatsappTemplateMetaUpload: typeof whatsappTemplateMetaUpload;
  whatsappTemplateMigration: typeof whatsappTemplateMigration;
  whatsappTemplatePresentation: typeof whatsappTemplatePresentation;
  whatsappTemplateQueries: typeof whatsappTemplateQueries;
  whatsappTemplateRender: typeof whatsappTemplateRender;
  whatsappTemplateSendPayload: typeof whatsappTemplateSendPayload;
  whatsappTemplateSendPayloadBuild: typeof whatsappTemplateSendPayloadBuild;
  whatsappTemplateUpdate: typeof whatsappTemplateUpdate;
  whatsappTemplateUpdateHelpers: typeof whatsappTemplateUpdateHelpers;
  whatsappTemplateWebhook: typeof whatsappTemplateWebhook;
  whatsappTemplates: typeof whatsappTemplates;
  whatsappTemplatesAction: typeof whatsappTemplatesAction;
  whatsappWebhook: typeof whatsappWebhook;
  workflowAppointmentServices: typeof workflowAppointmentServices;
  workflowAutomationConfig: typeof workflowAutomationConfig;
  workflowAutomationCost: typeof workflowAutomationCost;
  workflowAutomationCostMigration: typeof workflowAutomationCostMigration;
  workflowAutomationHistory: typeof workflowAutomationHistory;
  workflowAutomationLifecycle: typeof workflowAutomationLifecycle;
  workflowAutomationMessageActivity: typeof workflowAutomationMessageActivity;
  workflowAutomationOutbound: typeof workflowAutomationOutbound;
  workflowAutomationReconciliation: typeof workflowAutomationReconciliation;
  workflowAutomationSave: typeof workflowAutomationSave;
  workflowAutomationSchema: typeof workflowAutomationSchema;
  workflowAutomationValidators: typeof workflowAutomationValidators;
  workflowCore: typeof workflowCore;
  workflowDraftSave: typeof workflowDraftSave;
  workflowDraftValidation: typeof workflowDraftValidation;
  workflowFollowUpPool: typeof workflowFollowUpPool;
  workflowFollowUpRuntime: typeof workflowFollowUpRuntime;
  workflowFollowUpStartAfterMigration: typeof workflowFollowUpStartAfterMigration;
  workflowFollowUpTimer: typeof workflowFollowUpTimer;
  workflowFollowUpWorker: typeof workflowFollowUpWorker;
  workflowGraphSaveValidators: typeof workflowGraphSaveValidators;
  workflowLayout: typeof workflowLayout;
  workflowMedia: typeof workflowMedia;
  workflowMediaDeletion: typeof workflowMediaDeletion;
  workflowMediaInternal: typeof workflowMediaInternal;
  workflowMediaShared: typeof workflowMediaShared;
  workflowMessageGraphSave: typeof workflowMessageGraphSave;
  workflowMigrations: typeof workflowMigrations;
  workflowNodeCanvasControls: typeof workflowNodeCanvasControls;
  workflowNodeConfig: typeof workflowNodeConfig;
  workflowNodeReadiness: typeof workflowNodeReadiness;
  workflowNodeReadinessMigration: typeof workflowNodeReadinessMigration;
  workflowNodeRemoval: typeof workflowNodeRemoval;
  workflowReminderPool: typeof workflowReminderPool;
  workflowReminderRuntime: typeof workflowReminderRuntime;
  workflowReminderSchedule: typeof workflowReminderSchedule;
  workflowReminderWorker: typeof workflowReminderWorker;
  workflowReset: typeof workflowReset;
  workflowRuntimeContext: typeof workflowRuntimeContext;
  workflowTemplateUsage: typeof workflowTemplateUsage;
  workflowTemplateUsageSchema: typeof workflowTemplateUsageSchema;
  workflowValidators: typeof workflowValidators;
  workflowWhatsappTemplateSender: typeof workflowWhatsappTemplateSender;
  workflows: typeof workflows;
  workosClient: typeof workosClient;
  workosOrganizationActions: typeof workosOrganizationActions;
  workosWebhook: typeof workosWebhook;
  workpool: typeof workpool;
  workspaceSetupChecklist: typeof workspaceSetupChecklist;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  stripe: import("@convex-dev/stripe/_generated/component.js").ComponentApi<"stripe">;
  r2: import("@convex-dev/r2/_generated/component.js").ComponentApi<"r2">;
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  cfUploadWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"cfUploadWorkpool">;
  cfDeleteWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"cfDeleteWorkpool">;
  webScraperWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"webScraperWorkpool">;
  linkDiscovererWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"linkDiscovererWorkpool">;
  instagramSyncWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"instagramSyncWorkpool">;
  messengerSyncWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"messengerSyncWorkpool">;
  whatsappSyncWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"whatsappSyncWorkpool">;
  inboxAiReplyWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"inboxAiReplyWorkpool">;
  inboundMediaUnderstandingWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"inboundMediaUnderstandingWorkpool">;
  metaIndicatorWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"metaIndicatorWorkpool">;
  metaReactionWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"metaReactionWorkpool">;
  mediaDeleteWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"mediaDeleteWorkpool">;
  threadSummarizerWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"threadSummarizerWorkpool">;
  leadLabelWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"leadLabelWorkpool">;
  broadcastWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"broadcastWorkpool">;
  followUpWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"followUpWorkpool">;
  workflowReminderWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"workflowReminderWorkpool">;
  telegramNotificationWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"telegramNotificationWorkpool">;
  workflowFollowUpWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"workflowFollowUpWorkpool">;
  whatsappTemplateMediaWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"whatsappTemplateMediaWorkpool">;
  conversationLogWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"conversationLogWorkpool">;
  creditPeriodWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"creditPeriodWorkpool">;
  customerImportWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"customerImportWorkpool">;
  advancedAnalyticsWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"advancedAnalyticsWorkpool">;
  teamDeletionWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"teamDeletionWorkpool">;
  workOSAuthKit: import("@convex-dev/workos-authkit/_generated/component.js").ComponentApi<"workOSAuthKit">;
  crons: import("@convex-dev/crons/_generated/component.js").ComponentApi<"crons">;
  modelLifetimeUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"modelLifetimeUsage">;
  modelMonthlyUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"modelMonthlyUsage">;
  agentMonthlyUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"agentMonthlyUsage">;
  agentCostUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"agentCostUsage">;
  agentTokenUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"agentTokenUsage">;
  creditDailyUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"creditDailyUsage">;
  creditWorkspaceDailyUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"creditWorkspaceDailyUsage">;
  creditAccountDailyUsage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"creditAccountDailyUsage">;
  analyticsMetrics: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"analyticsMetrics">;
  agentOverviewAiAssistedDaily: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"agentOverviewAiAssistedDaily">;
  agentOverviewHumanEscalationsDaily: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"agentOverviewHumanEscalationsDaily">;
};
