import { readFileSync } from 'node:fs';
import { expect, test } from 'vitest';

function source(path: string) {
  return readFileSync(new URL(path, import.meta.url), 'utf8');
}

test('adds separate paginated history dialogs to both workflow cards', () => {
  const dialog = source('./WorkflowAutomationHistoryDialog.tsx');
  const pagination = source('./WorkflowAutomationHistoryPager.tsx');
  const reminderSetup = source('./WorkflowReminderSetupNode.tsx');
  const followupSetup = source('./WorkflowFollowupSetupNode.tsx');
  const reminderSummary = source('./WorkflowReminderSummaryNode.tsx');
  const followupSummary = source('./WorkflowFollowupSummaryNode.tsx');
  expect(dialog).toContain('api.workflowAutomationHistory.list');
  expect(dialog).toContain('const PAGE_SIZE = 25');
  expect(dialog).toContain('initialNumItems: PAGE_SIZE');
  expect(dialog).toContain('scheduled');
  expect(dialog).toContain('sent');
  expect(dialog).toContain('failed');
  expect(dialog).toContain('skipped');
  expect(dialog).toContain('cancelled');
  expect(reminderSetup).not.toContain('<WorkflowAutomationHistoryDialog');
  expect(followupSetup).not.toContain('<WorkflowAutomationHistoryDialog');
  expect(reminderSummary).toContain('<WorkflowAutomationHistoryDialog');
  expect(reminderSummary).toContain('automationKind="reminder"');
  expect(followupSummary).toContain('<WorkflowAutomationHistoryDialog');
  expect(followupSummary).toContain('automationKind="followUp"');
  expect(reminderSummary).toContain('className="flex items-center justify-between gap-3"');
  expect(followupSummary).toContain('className="flex items-center justify-between gap-3"');
  expect(dialog).toContain('variant="outline"');
  expect(dialog).toContain('size="sm"');
  expect(dialog).toContain('<History data-icon="inline-start" />');
  expect(dialog).toContain('<DialogContent className="w-max max-w-none rounded-2xl p-6 sm:max-w-none sm:p-8">');
  expect(dialog).toContain('<div className="w-max [&_[data-slot=table-container]]:overflow-visible">');
  expect(dialog).toContain('<Table className="w-max">');
  expect(dialog).not.toContain("from '@/components/ui/scroll-area'");
  expect(dialog).not.toContain('<ScrollArea');
  expect(dialog).not.toContain('sm:max-w-3xl');
  expect(dialog).toContain('<Empty className="rounded-xl border bg-muted/60 px-8 py-10">');
  expect(dialog).toContain("from '@/components/ui/table'");
  expect(dialog).not.toContain('<Table>');
  expect(dialog).toContain('<TableCaption>{tableCaption}</TableCaption>');
  expect(dialog).toContain('formatWorkflowAutomationHistoryCaption');
  expect(dialog).toContain('sentCount: estimatedTotal?.sentCount ?? 0');
  expect(pagination).toContain("from '@/components/ui/pagination'");
  expect(pagination).toContain('<Pagination');
  expect(pagination).toContain('<PaginationPrevious');
  expect(pagination).toContain('<PaginationLink');
  expect(pagination).toContain('<PaginationEllipsis');
  expect(pagination).toContain('<PaginationNext');
  expect(pagination).toContain('getWorkflowAutomationHistoryPageNumbers');
  expect(dialog).toContain('results.slice(');
  expect(dialog).toContain('void loadMore(PAGE_SIZE)');
  expect(dialog).not.toContain('Load more');
  expect(dialog).not.toContain("'Reminder automation activity for this agent.'");
  expect(dialog).not.toContain("'Follow-up automation activity for this agent.'");
  expect(dialog).toContain('<TableHeader>');
  expect(dialog).toContain('<TableBody>');
  expect(dialog).toContain('<TableHead>Customer</TableHead>');
  expect(dialog).toContain('<TableHead>Template</TableHead>');
  expect(dialog).toContain('<TableHead>Scheduled</TableHead>');
  expect(dialog).toContain('<TableHead>Sent</TableHead>');
  expect(dialog).toContain('<TableHead>Status</TableHead>');
  expect(dialog).toContain('<TableHead className="text-right">Estimated cost</TableHead>');
  expect(dialog).toContain('<TableFooter>');
  expect(dialog).toContain('Estimated total spent');
  expect(dialog).toContain('estimatedTotal.estimatedTotalSpentMyr');
  expect(dialog).toContain('api.workflowAutomationHistory.estimatedTotal');
  expect(dialog).toContain('unpricedSentCount');
  expect(dialog).toContain('showsOperationalReason(item.status) && item.reason');
  expect(dialog).not.toContain('Scope:');
  expect(dialog).not.toContain('Attempt:');
  expect(dialog).not.toContain('className="flex flex-col gap-2 rounded-xl border p-4"');
});
